//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfNodes.Entity
{
    using System;
    using System.ComponentModel;

    public partial class TablesNodes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TablesNodes()
        {
            this.TablesNodes1 = new BindingList<TablesNodes>();
        }
    
        public int Id { get; set; }
        public string NameNode { get; set; }
        public Nullable<int> ParentId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual BindingList<TablesNodes> TablesNodes1 { get; set; }
        public virtual TablesNodes TablesNodes2 { get; set; }
    }
}
